apiVersion: v1
kind: Service
metadata:
  name: cen4802-fibonacci-service
spec:
  type: NodePort
  selector:
    app: cen4802-fibonacci
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080